### ISSUE TITLE
define xml file domain not showing on vmm

### ISSUE THREAD

**Issue by ghost** [PassthroughPOST/Hackintosh-KVM#2]
I defined the intel XML file and it is not showing up on the vmm list
any suggestions?

**Comment by SharkWipf** [comment]
If it defined without errors, you might be connecting to the wrong user's Libvirt session with either virt-manager or virsh.
Did you get any errors? If not, it's not an issue with the XML.

**Comment by ghost** [comment]
nope I did not

**Comment by ghost** [comment]
can you try and help me config the xml correctly?

**Comment by SharkWipf** [comment]
That is a question better suited for our [Discord](https://discord.gg/Efa2Ndb), where we can help you with these kinds of problems more easily, instead of in the Github issue tracker.
I won't be able to help you there myself atm as I'm heading to bed, but there's other people who will be able to help you out there.
